# Generated by Django 2.1.2 on 2019-03-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filter_annotation_ids',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
