# Generated by Django 2.1.2 on 2019-03-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_filter_annotation_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='split_type',
            field=models.CharField(choices=[('split', 'split'), ('match', 'match')], default='split', max_length=30),
        ),
    ]
