# Generated by Django 2.1.2 on 2019-03-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190318_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guideline',
            field=models.TextField(blank=True),
        ),
    ]
